"""
Django settings for novaerp_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar el archivo .env
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x#zw4le!6-h1cq!l$re64yjn_45=(u6-t2ff77%4o#vwgq5*hh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# RF-20/RN01: la bitacora registra la IP de origen. Detras de un reverse proxy
# REMOTE_ADDR es la del proxy, no la del cliente. Activar solo cuando exista un
# proxy de confianza que reescriba la cabecera: si se confia en X-Forwarded-For
# sin proxy delante, cualquier cliente puede falsear la IP que queda auditada.
USE_X_FORWARDED_FOR = os.getenv('USE_X_FORWARDED_FOR', 'False').strip().lower() in ('1', 'true')

# RF-25: entrega de notificaciones por correo. Solo se usa el framework de
# email de Django (sin librerias nuevas). En dev el backend por defecto imprime
# a consola; en produccion se configura SMTP por variables de entorno. El worker
# `manage.py enviar_notificaciones` drena la cola (core.notificacion).
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@novaerp.local')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').strip().lower() in ('1', 'true')

# Expiracion del JWT del portal de plataforma (SysAdmin). El SysAdmin no
# pertenece a ningun tenant, asi que no hay config_seguridad_tenant que leer:
# la expiracion se configura por entorno aqui (default 8h, como los tenants).
SYSADMIN_JWT_EXPIRACION_HORAS = int(os.getenv('SYSADMIN_JWT_EXPIRACION_HORAS', '8'))


# Application definition

# Modifica la lista de aplicaciones instaladas
INSTALLED_APPS = [
    # Sin contenttypes/auth/sessions/admin/messages: no los necesitamos y
    # así nunca se crean tablas django_* en la base de datos.
    'django.contrib.staticfiles',
    'corsheaders',

    # Tus apps de dominio (una por esquema de Postgres)
    'core',
    'ventas',
    'inventario',
    'compras',
    'finanzas',
    'rrhh',
    'proyectos',
    'bpm',
    'bi',
    'reglas',
]

# Modifica los Middlewares quitando las sesiones y auth antiguas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.auth_middleware.JWTCustomMiddleware',
]

# CORS: el frontend (Angular) corre en un origen distinto durante desarrollo.
# CORS_ALLOWED_ORIGINS por .env, coma-separado (sin barra final). El login
# manda el JWT en el header Authorization, no en cookies, asi que por ahora
# no se necesita CORS_ALLOW_CREDENTIALS.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:4200').split(',') if o.strip()
]

ROOT_URLCONF = 'novaerp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'novaerp_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
